filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /code/logs/**/*.log # Путь к логам внутри контейнера
    fields:
      project: payment_service_api # Имя проекта с префиксом сервиса
      type: python_log # Тип лога (по умолчанию лучше оставить python_log)
    fields_under_root: true # Настройки паттерна для объединения логов
    multiline.pattern: '^\[log_start\]' # Настройки паттерна для объединения логов
    multiline.negate: true # Настройки паттерна для объединения логов
    multiline.match: after # Настройки паттерна для объединения логов

output.logstash:
  hosts: ["receiver.rlt.pw:5044"] # IP и порт Logstash
  ssl:
    certificate_authorities: ["/code/certs/logstash_ca.crt"]
    verification_mode: full
